// <auto-generated />
using System;
using BasicWebApi.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BasicWebApi.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(16,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 2, 20, 10, 13, 39, 478, DateTimeKind.Local).AddTicks(4096),
                            Name = "Iphone 12",
                            Price = 1000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 2, 18, 10, 13, 39, 478, DateTimeKind.Local).AddTicks(4103),
                            Name = "Acer Laptop",
                            Price = 2000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 2, 21, 10, 13, 39, 478, DateTimeKind.Local).AddTicks(4105),
                            Name = "Samsung S21",
                            Price = 1500m,
                            Stock = 200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
